//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/DPad_Control.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DPad_Control: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DPad_Control()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DPad_Control"",
    ""maps"": [
        {
            ""name"": ""DPadContol"",
            ""id"": ""0436f594-6010-4ebc-b3d5-cc1f7b750fbe"",
            ""actions"": [
                {
                    ""name"": ""ThrottleYaw"",
                    ""type"": ""Value"",
                    ""id"": ""35bcc9ba-a022-4d74-b41a-5c789f2a51d4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PitchRoll"",
                    ""type"": ""Value"",
                    ""id"": ""845c6f04-2883-4e4f-b002-47dc0febe6dc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlayerMovement"",
                    ""type"": ""Value"",
                    ""id"": ""348fad1c-6f1d-4639-becf-118d28f1e17f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""ae1e0764-b0a0-4507-a386-e356a01a7bbb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spray"",
                    ""type"": ""Button"",
                    ""id"": ""a6fb989a-30a1-4948-9bfc-d94682bbaab1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""a1444738-f01d-4bab-b210-bf913dca31c3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleYaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bc56f440-d5d5-418a-b84a-cefbb925c830"",
                    ""path"": ""<Keyboard>/#(W)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleYaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ebc63458-aacd-427c-9cc6-b7cb406fe8dd"",
                    ""path"": ""<Keyboard>/#(S)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleYaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3500abe0-e5ef-48ba-863f-5adb616ce35a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleYaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ccc42633-a019-4b9d-b5c1-5ae8b0a087be"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleYaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left stick"",
                    ""id"": ""a933e065-4756-4292-882b-4b70bbf62b2f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleYaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c265bfb2-94d1-49fe-ad96-d075af679247"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleYaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2b44f32f-e01b-49a6-9705-80f010e4ee24"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleYaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ccda8110-155c-4131-8d04-4fc772e4a276"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleYaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e8dc32ee-fbb6-4f76-ad1b-881fa6d28e59"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrottleYaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow keys"",
                    ""id"": ""7d7e6b6f-13b9-48e4-ac85-64a21da5ba9a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3e33e30c-b59f-4f75-8e0f-f5ed8d3d3257"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a0ff9ef2-7407-42f1-b1d7-462b8f5b7a55"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e44e1f58-8c6c-4319-9cce-0f3475f4a26d"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""00090af8-b6f7-48ed-bf7b-f5dd8236457e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right stick"",
                    ""id"": ""4be4c9f2-7648-4d4d-9c88-139999abe8d6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""efb1461a-5d87-4765-ab2d-e31032f83b9a"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""aebb2084-63a8-4e4d-a3fa-781e52ca08fe"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e7b10d2f-2a80-44c4-a036-7828adb20c7b"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""959fb068-5f3b-4500-96d3-cdec6b71aff1"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""DPadArrows"",
                    ""id"": ""3c6c580f-a096-4e85-b964-3ba23465fb0c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ad268e7d-97c7-451f-9dae-c3c7f304b661"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cdb8dcec-af09-4611-bc78-ce7e3fe63103"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4eb3f18d-ae7a-4176-9158-1f9561e6f57f"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8e68f9e6-9485-4122-9910-e503dd6f9216"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9409586a-64ef-4a1c-8bfe-9461f2f1cb3b"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64a47347-e9d8-48e5-98ed-26449a948282"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spray"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DPadContol
        m_DPadContol = asset.FindActionMap("DPadContol", throwIfNotFound: true);
        m_DPadContol_ThrottleYaw = m_DPadContol.FindAction("ThrottleYaw", throwIfNotFound: true);
        m_DPadContol_PitchRoll = m_DPadContol.FindAction("PitchRoll", throwIfNotFound: true);
        m_DPadContol_PlayerMovement = m_DPadContol.FindAction("PlayerMovement", throwIfNotFound: true);
        m_DPadContol_Jump = m_DPadContol.FindAction("Jump", throwIfNotFound: true);
        m_DPadContol_Spray = m_DPadContol.FindAction("Spray", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DPadContol
    private readonly InputActionMap m_DPadContol;
    private List<IDPadContolActions> m_DPadContolActionsCallbackInterfaces = new List<IDPadContolActions>();
    private readonly InputAction m_DPadContol_ThrottleYaw;
    private readonly InputAction m_DPadContol_PitchRoll;
    private readonly InputAction m_DPadContol_PlayerMovement;
    private readonly InputAction m_DPadContol_Jump;
    private readonly InputAction m_DPadContol_Spray;
    public struct DPadContolActions
    {
        private @DPad_Control m_Wrapper;
        public DPadContolActions(@DPad_Control wrapper) { m_Wrapper = wrapper; }
        public InputAction @ThrottleYaw => m_Wrapper.m_DPadContol_ThrottleYaw;
        public InputAction @PitchRoll => m_Wrapper.m_DPadContol_PitchRoll;
        public InputAction @PlayerMovement => m_Wrapper.m_DPadContol_PlayerMovement;
        public InputAction @Jump => m_Wrapper.m_DPadContol_Jump;
        public InputAction @Spray => m_Wrapper.m_DPadContol_Spray;
        public InputActionMap Get() { return m_Wrapper.m_DPadContol; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DPadContolActions set) { return set.Get(); }
        public void AddCallbacks(IDPadContolActions instance)
        {
            if (instance == null || m_Wrapper.m_DPadContolActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DPadContolActionsCallbackInterfaces.Add(instance);
            @ThrottleYaw.started += instance.OnThrottleYaw;
            @ThrottleYaw.performed += instance.OnThrottleYaw;
            @ThrottleYaw.canceled += instance.OnThrottleYaw;
            @PitchRoll.started += instance.OnPitchRoll;
            @PitchRoll.performed += instance.OnPitchRoll;
            @PitchRoll.canceled += instance.OnPitchRoll;
            @PlayerMovement.started += instance.OnPlayerMovement;
            @PlayerMovement.performed += instance.OnPlayerMovement;
            @PlayerMovement.canceled += instance.OnPlayerMovement;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Spray.started += instance.OnSpray;
            @Spray.performed += instance.OnSpray;
            @Spray.canceled += instance.OnSpray;
        }

        private void UnregisterCallbacks(IDPadContolActions instance)
        {
            @ThrottleYaw.started -= instance.OnThrottleYaw;
            @ThrottleYaw.performed -= instance.OnThrottleYaw;
            @ThrottleYaw.canceled -= instance.OnThrottleYaw;
            @PitchRoll.started -= instance.OnPitchRoll;
            @PitchRoll.performed -= instance.OnPitchRoll;
            @PitchRoll.canceled -= instance.OnPitchRoll;
            @PlayerMovement.started -= instance.OnPlayerMovement;
            @PlayerMovement.performed -= instance.OnPlayerMovement;
            @PlayerMovement.canceled -= instance.OnPlayerMovement;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Spray.started -= instance.OnSpray;
            @Spray.performed -= instance.OnSpray;
            @Spray.canceled -= instance.OnSpray;
        }

        public void RemoveCallbacks(IDPadContolActions instance)
        {
            if (m_Wrapper.m_DPadContolActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDPadContolActions instance)
        {
            foreach (var item in m_Wrapper.m_DPadContolActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DPadContolActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DPadContolActions @DPadContol => new DPadContolActions(this);
    public interface IDPadContolActions
    {
        void OnThrottleYaw(InputAction.CallbackContext context);
        void OnPitchRoll(InputAction.CallbackContext context);
        void OnPlayerMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSpray(InputAction.CallbackContext context);
    }
}
